import {
  LayoutDashboard,
  Receipt,
  Shirt,
  Boxes,
  ShoppingBag,
  TrendingUp,
  Users,
  Truck,
  MapPin,
  UserCheck,
  ShieldCheck,
  Wallet,
  Landmark,
  ScanBarcode,
  BarChart3,
  LineChart,
  Bell,
  Building,
  Settings,
  History,
  UserCircle,
} from "lucide-react";
import { ROUTES } from "../../../constants/routes.js";

export const SIDEBAR_MENU_DATA = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: LayoutDashboard,
    to: ROUTES.DASHBOARD,
  },
  {
    id: "pos",
    title: "POS",
    icon: Receipt,
    badge: "Fast Billing",
    to: ROUTES.BILLING,
    children: [
      { id: "pos-new-sale", title: "New Sale", to: "/billing?view=new" },
      { id: "pos-sales-invoice", title: "Sales Invoice", to: "/billing?view=invoices" },
      { id: "pos-hold-bills", title: "Hold Bills", to: "/billing?view=hold", badge: "2" },
      { id: "pos-quotation", title: "Quotation", to: "/billing?view=quotations" },
      { id: "pos-returns", title: "Returns", to: "/billing?view=returns" },
      { id: "pos-exchanges", title: "Exchanges", to: "/billing?view=exchanges" },
      { id: "pos-customers", title: "Customers", to: "/customers" },
      { id: "pos-settings", title: "POS Settings", to: "/settings?tab=store" },
    ],
  },
  {
    id: "products",
    title: "Products",
    icon: Shirt,
    to: ROUTES.PRODUCTS,
    children: [
      { id: "prod-all", title: "All Products", to: "/products" },
      { id: "prod-add", title: "Add Product", to: "/products/new" },
      { id: "prod-variants", title: "Product Variants", to: "/products/variants" },
      { id: "prod-categories", title: "Categories", to: "/products/categories" },
      { id: "prod-subcategories", title: "Subcategories", to: "/products/subcategories" },
      { id: "prod-brands", title: "Brands", to: "/products/brands" },
      { id: "prod-types", title: "Product Types", to: "/products/types" },
      { id: "prod-materials", title: "Materials", to: "/products/materials" },
      { id: "prod-colors", title: "Colors", to: "/products/colors" },
      { id: "prod-size-groups", title: "Size Groups", to: "/products/size-groups" },
      { id: "prod-sizes", title: "Sizes", to: "/products/sizes" },
      { id: "prod-units", title: "Units", to: "/products/units" },
      { id: "prod-images", title: "Product Images", to: "/products/images" },
      { id: "prod-barcodes", title: "Product Barcodes", to: "/products/barcodes" },
      { id: "prod-prices", title: "Product Prices", to: "/products/prices" },
      { id: "prod-price-history", title: "Price History", to: "/products/price-history" },
      { id: "prod-taxes", title: "Taxes", to: "/products/taxes" },
      { id: "prod-discounts", title: "Discounts", to: "/products/discounts" },
    ],
  },
  {
    id: "inventory",
    title: "Inventory",
    icon: Boxes,
    to: ROUTES.STOCK,
    children: [
      { id: "inv-overview", title: "Stock Overview", to: "/stock" },
      { id: "inv-by-branch", title: "Stock by Branch", to: "/stock/branches" },
      { id: "inv-by-location", title: "Stock by Location", to: "/stock/locations" },
      { id: "inv-in", title: "Stock In", to: "/stock/in" },
      { id: "inv-out", title: "Stock Out", to: "/stock/out" },
      { id: "inv-transfer", title: "Stock Transfer", to: "/stock/transfer" },
      { id: "inv-adjustment", title: "Stock Adjustment", to: "/stock/adjustment" },
      { id: "inv-damaged", title: "Damaged Stock", to: "/stock/damaged" },
      { id: "inv-lost", title: "Lost Stock", to: "/stock/lost" },
      { id: "inv-low", title: "Low Stock", to: "/stock/low", badge: "3" },
      { id: "inv-out-of-stock", title: "Out of Stock", to: "/stock/out-of-stock" },
      { id: "inv-valuation", title: "Stock Valuation", to: "/stock/valuation" },
      { id: "inv-movement", title: "Stock Movement History", to: "/stock/movement" },
    ],
  },
  {
    id: "purchases",
    title: "Purchases",
    icon: ShoppingBag,
    to: ROUTES.PURCHASES,
    children: [
      { id: "pur-dashboard", title: "Purchase Dashboard", to: "/purchases" },
      { id: "pur-new", title: "New Purchase", to: "/purchases/new" },
      { id: "pur-invoices", title: "Purchase Invoices", to: "/purchases/invoices" },
      { id: "pur-returns", title: "Purchase Returns", to: "/purchases/returns" },
      { id: "pur-payments", title: "Purchase Payments", to: "/purchases/payments" },
      { id: "pur-suppliers", title: "Suppliers", to: "/suppliers" },
      { id: "pur-transactions", title: "Supplier Transactions", to: "/purchases/transactions" },
    ],
  },
  {
    id: "sales",
    title: "Sales",
    icon: TrendingUp,
    to: "/sales",
    children: [
      { id: "sale-dashboard", title: "Sales Dashboard", to: "/sales" },
      { id: "sale-all", title: "All Sales", to: "/sales/all" },
      { id: "sale-new", title: "New Sale", to: "/billing?view=new" },
      { id: "sale-invoices", title: "Sales Invoices", to: "/billing?view=invoices" },
      { id: "sale-returns", title: "Sales Returns", to: "/sales/returns" },
      { id: "sale-payments", title: "Sale Payments", to: "/sales/payments" },
      { id: "sale-exchanges", title: "Exchanges", to: "/sales/exchanges" },
      { id: "sale-cancelled", title: "Cancelled Sales", to: "/sales/cancelled" },
    ],
  },
  {
    id: "customers",
    title: "Customers",
    icon: Users,
    to: ROUTES.CUSTOMERS,
    children: [
      { id: "cust-all", title: "All Customers", to: "/customers" },
      { id: "cust-add", title: "Add Customer", to: "/customers/new" },
      { id: "cust-groups", title: "Customer Groups", to: "/customers/groups" },
      { id: "cust-transactions", title: "Customer Transactions", to: "/customers/transactions" },
      { id: "cust-payments", title: "Customer Payments", to: "/customers/payments" },
      { id: "cust-due", title: "Customer Due", to: "/customers/due" },
      { id: "cust-history", title: "Customer Purchase History", to: "/customers/history" },
      { id: "cust-statements", title: "Customer Statements", to: "/customers/statements" },
    ],
  },
  {
    id: "suppliers",
    title: "Suppliers",
    icon: Truck,
    to: ROUTES.SUPPLIERS,
    children: [
      { id: "sup-all", title: "All Suppliers", to: "/suppliers" },
      { id: "sup-add", title: "Add Supplier", to: "/suppliers/new" },
      { id: "sup-groups", title: "Supplier Groups", to: "/suppliers/groups" },
      { id: "sup-transactions", title: "Supplier Transactions", to: "/suppliers/transactions" },
      { id: "sup-payments", title: "Supplier Payments", to: "/suppliers/payments" },
      { id: "sup-due", title: "Supplier Due", to: "/suppliers/due" },
      { id: "sup-history", title: "Purchase History", to: "/suppliers/history" },
      { id: "sup-statements", title: "Supplier Statements", to: "/suppliers/statements" },
    ],
  },
  {
    id: "branches",
    title: "Branches & Locations",
    icon: MapPin,
    to: "/branches",
    children: [
      { id: "br-all", title: "Branches", to: "/branches" },
      { id: "br-addresses", title: "Branch Addresses", to: "/branches/addresses" },
      { id: "br-warehouses", title: "Warehouses", to: "/branches/warehouses" },
      { id: "br-floors", title: "Floors", to: "/branches/floors" },
      { id: "br-departments", title: "Departments", to: "/branches/departments" },
      { id: "br-racks", title: "Racks", to: "/branches/racks" },
      { id: "br-shelves", title: "Shelves", to: "/branches/shelves" },
      { id: "br-stock-locations", title: "Stock Locations", to: "/branches/locations" },
    ],
  },
  {
    id: "employees",
    title: "Employees",
    icon: UserCheck,
    to: ROUTES.EMPLOYEES,
    children: [
      { id: "emp-all", title: "All Employees", to: "/employees" },
      { id: "emp-add", title: "Add Employee", to: "/employees/new" },
      { id: "emp-departments", title: "Departments", to: "/employees/departments" },
      { id: "emp-designations", title: "Designations", to: "/employees/designations" },
      { id: "emp-documents", title: "Employee Documents", to: "/employees/documents" },
      { id: "emp-shifts", title: "Employee Shifts", to: "/employees/shifts" },
      { id: "emp-attendance", title: "Attendance", to: "/attendance" },
      { id: "emp-leave", title: "Leave Management", to: "/employees/leaves" },
      { id: "emp-reports", title: "Employee Reports", to: "/employees/reports" },
    ],
  },
  {
    id: "users-access",
    title: "Users & Access",
    icon: ShieldCheck,
    to: "/users",
    children: [
      { id: "usr-all", title: "Users", to: "/users" },
      { id: "usr-roles", title: "Roles", to: "/users/roles" },
      { id: "usr-permissions", title: "Permissions", to: "/users/permissions" },
      { id: "usr-user-roles", title: "User Roles", to: "/users/user-roles" },
      { id: "usr-sessions", title: "User Sessions", to: "/users/sessions" },
      { id: "usr-login-history", title: "Login History", to: "/users/login-history" },
      { id: "usr-password-history", title: "Password History", to: "/users/password-history" },
      { id: "usr-access-control", title: "Access Control", to: "/users/access-control" },
    ],
  },
  {
    id: "finance",
    title: "Cash & Finance",
    icon: Wallet,
    to: "/finance",
    children: [
      { id: "fin-dashboard", title: "Finance Dashboard", to: "/finance" },
      { id: "fin-cash-registers", title: "Cash Registers", to: "/finance/registers" },
      { id: "fin-register-sessions", title: "Register Sessions", to: "/finance/register-sessions" },
      { id: "fin-cash-transactions", title: "Cash Transactions", to: "/finance/cash-transactions" },
      { id: "fin-bank-accounts", title: "Bank Accounts", to: "/finance/bank-accounts" },
      { id: "fin-bank-transactions", title: "Bank Transactions", to: "/finance/bank-transactions" },
      { id: "fin-income", title: "Income", to: "/finance/income" },
      { id: "fin-expenses", title: "Expenses", to: "/finance/expenses" },
      { id: "fin-expense-categories", title: "Expense Categories", to: "/finance/expense-categories" },
      { id: "fin-receivables", title: "Customer Receivables", to: "/finance/receivables" },
      { id: "fin-payables", title: "Supplier Payables", to: "/finance/payables" },
      { id: "fin-statements", title: "Financial Statements", to: "/finance/statements" },
    ],
  },
  {
    id: "banks",
    title: "Banks",
    icon: Landmark,
    to: "/banks",
    children: [
      { id: "bnk-all", title: "Banks", to: "/banks" },
      { id: "bnk-company-accounts", title: "Company Bank Accounts", to: "/banks/company-accounts" },
      { id: "bnk-transactions", title: "Bank Transactions", to: "/banks/transactions" },
      { id: "bnk-deposit", title: "Cash Deposit", to: "/banks/deposit" },
      { id: "bnk-withdrawal", title: "Cash Withdrawal", to: "/banks/withdrawal" },
      { id: "bnk-transfer", title: "Bank Transfer", to: "/banks/transfer" },
    ],
  },
  {
    id: "barcodes",
    title: "Barcode & Labels",
    icon: ScanBarcode,
    to: "/barcodes",
    children: [
      { id: "bar-generator", title: "Barcode Generator", to: "/barcodes/generator" },
      { id: "bar-templates", title: "Barcode Templates", to: "/barcodes/templates" },
      { id: "bar-print", title: "Print Barcodes", to: "/barcodes/print" },
      { id: "bar-print-history", title: "Print History", to: "/barcodes/print-history" },
      { id: "bar-label-templates", title: "Label Templates", to: "/barcodes/label-templates" },
      { id: "bar-settings", title: "Barcode Settings", to: "/barcodes/settings" },
    ],
  },
  {
    id: "reports",
    title: "Reports",
    icon: BarChart3,
    to: ROUTES.REPORTS,
    children: [
      {
        id: "rep-sales",
        title: "Sales Reports",
        children: [
          { id: "rep-sales-daily", title: "Daily Sales", to: "/reports/sales/daily" },
          { id: "rep-sales-monthly", title: "Monthly Sales", to: "/reports/sales/monthly" },
          { id: "rep-sales-product", title: "Sales by Product", to: "/reports/sales/product" },
          { id: "rep-sales-category", title: "Sales by Category", to: "/reports/sales/category" },
          { id: "rep-sales-brand", title: "Sales by Brand", to: "/reports/sales/brand" },
          { id: "rep-sales-employee", title: "Sales by Employee", to: "/reports/sales/employee" },
          { id: "rep-sales-payment", title: "Sales by Payment Method", to: "/reports/sales/payment" },
        ],
      },
      {
        id: "rep-purchases",
        title: "Purchase Reports",
        children: [
          { id: "rep-pur-summary", title: "Purchase Summary", to: "/reports/purchases/summary" },
          { id: "rep-pur-supplier", title: "Purchase by Supplier", to: "/reports/purchases/supplier" },
          { id: "rep-pur-product", title: "Purchase by Product", to: "/reports/purchases/product" },
          { id: "rep-pur-returns", title: "Purchase Returns", to: "/reports/purchases/returns" },
        ],
      },
      {
        id: "rep-inventory",
        title: "Inventory Reports",
        children: [
          { id: "rep-inv-current", title: "Current Stock", to: "/reports/inventory/current" },
          { id: "rep-inv-movement", title: "Stock Movement", to: "/reports/inventory/movement" },
          { id: "rep-inv-valuation", title: "Stock Valuation", to: "/reports/inventory/valuation" },
          { id: "rep-inv-low", title: "Low Stock", to: "/reports/inventory/low" },
          { id: "rep-inv-dead", title: "Dead Stock", to: "/reports/inventory/dead" },
          { id: "rep-inv-fast", title: "Fast Moving Products", to: "/reports/inventory/fast" },
          { id: "rep-inv-slow", title: "Slow Moving Products", to: "/reports/inventory/slow" },
        ],
      },
      {
        id: "rep-customers",
        title: "Customer Reports",
        children: [
          { id: "rep-cust-sales", title: "Customer Sales", to: "/reports/customers/sales" },
          { id: "rep-cust-due", title: "Customer Due", to: "/reports/customers/due" },
          { id: "rep-cust-statements", title: "Customer Statements", to: "/reports/customers/statements" },
        ],
      },
      {
        id: "rep-suppliers",
        title: "Supplier Reports",
        children: [
          { id: "rep-sup-purchases", title: "Supplier Purchases", to: "/reports/suppliers/purchases" },
          { id: "rep-sup-due", title: "Supplier Due", to: "/reports/suppliers/due" },
          { id: "rep-sup-statements", title: "Supplier Statements", to: "/reports/suppliers/statements" },
        ],
      },
      {
        id: "rep-finance",
        title: "Finance Reports",
        children: [
          { id: "rep-fin-income", title: "Income Report", to: "/reports/finance/income" },
          { id: "rep-fin-expense", title: "Expense Report", to: "/reports/finance/expense" },
          { id: "rep-fin-cash", title: "Cash Report", to: "/reports/finance/cash" },
          { id: "rep-fin-bank", title: "Bank Report", to: "/reports/finance/bank" },
          { id: "rep-fin-pl", title: "Profit & Loss", to: "/reports/finance/pl" },
        ],
      },
      {
        id: "rep-tax",
        title: "Tax Reports",
        children: [
          { id: "rep-tax-summary", title: "Tax Summary", to: "/reports/tax/summary" },
          { id: "rep-tax-gst-sales", title: "GST Sales", to: "/reports/tax/gst-sales" },
          { id: "rep-tax-gst-purchases", title: "GST Purchases", to: "/reports/tax/gst-purchases" },
          { id: "rep-tax-collection", title: "Tax Collection", to: "/reports/tax/collection" },
        ],
      },
    ],
  },
  {
    id: "analytics",
    title: "Analytics",
    icon: LineChart,
    to: "/analytics",
    children: [
      { id: "ana-sales", title: "Sales Analytics", to: "/analytics/sales" },
      { id: "ana-product", title: "Product Analytics", to: "/analytics/products" },
      { id: "ana-inventory", title: "Inventory Analytics", to: "/analytics/inventory" },
      { id: "ana-customer", title: "Customer Analytics", to: "/analytics/customers" },
      { id: "ana-supplier", title: "Supplier Analytics", to: "/analytics/suppliers" },
      { id: "ana-profit", title: "Profit Analytics", to: "/analytics/profit" },
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    icon: Bell,
    badge: "5",
    to: "/notifications",
    children: [
      { id: "notif-all", title: "All Notifications", to: "/notifications" },
      { id: "notif-low-stock", title: "Low Stock Alerts", to: "/notifications/low-stock", badge: "2" },
      { id: "notif-payment-due", title: "Payment Due Alerts", to: "/notifications/payment-due" },
      { id: "notif-purchase", title: "Purchase Alerts", to: "/notifications/purchases" },
      { id: "notif-system", title: "System Notifications", to: "/notifications/system" },
    ],
  },
  {
    id: "company",
    title: "Company",
    icon: Building,
    to: "/company",
    children: [
      { id: "comp-profile", title: "Company Profile", to: "/company/profile" },
      { id: "comp-addresses", title: "Company Addresses", to: "/company/addresses" },
      { id: "comp-contacts", title: "Company Contacts", to: "/company/contacts" },
      { id: "comp-tax", title: "Tax Details", to: "/company/tax" },
      { id: "comp-bank-accounts", title: "Bank Accounts", to: "/company/bank-accounts" },
      { id: "comp-settings", title: "Business Settings", to: "/company/settings" },
      { id: "comp-sequences", title: "Number Sequences", to: "/company/sequences" },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: Settings,
    to: ROUTES.SETTINGS,
    children: [
      { id: "set-general", title: "General Settings", to: "/settings?tab=general" },
      { id: "set-pos", title: "POS Settings", to: "/settings?tab=store" },
      { id: "set-invoice", title: "Invoice Settings", to: "/settings?tab=store" },
      { id: "set-tax", title: "Tax Settings", to: "/settings?tab=store" },
      { id: "set-payment", title: "Payment Methods", to: "/settings?tab=store" },
      { id: "set-currency", title: "Currency", to: "/settings?tab=store" },
      { id: "set-datetime", title: "Date & Time", to: "/settings?tab=general" },
      { id: "set-receipt", title: "Receipt Settings", to: "/settings?tab=store" },
      { id: "set-printer", title: "Printer Settings", to: "/settings?tab=printer" },
      { id: "set-barcode", title: "Barcode Settings", to: "/barcodes/settings" },
      { id: "set-notif", title: "Notification Settings", to: "/settings?tab=notif" },
      { id: "set-system", title: "System Settings", to: "/settings?tab=fonts" },
    ],
  },
  {
    id: "audit",
    title: "Audit & Security",
    icon: History,
    to: "/audit",
    children: [
      { id: "aud-logs", title: "Audit Logs", to: "/audit/logs" },
      { id: "aud-activity", title: "Activity Logs", to: "/audit/activity" },
      { id: "aud-login-history", title: "Login History", to: "/audit/login-history" },
      { id: "aud-sessions", title: "User Sessions", to: "/audit/sessions" },
      { id: "aud-security-events", title: "Security Events", to: "/audit/security-events" },
      { id: "aud-api-logs", title: "API Logs", to: "/audit/api-logs" },
    ],
  },
  {
    id: "account",
    title: "My Account",
    icon: UserCircle,
    to: "/account",
    children: [
      { id: "acc-profile", title: "My Profile", to: "/settings?tab=profile" },
      { id: "acc-password", title: "Change Password", to: "/settings?tab=security" },
      { id: "acc-security", title: "Security", to: "/settings?tab=security" },
      { id: "acc-sessions", title: "Active Sessions", to: "/settings?tab=security" },
      { id: "acc-logout", title: "Logout", to: "/logout", isLogout: true },
    ],
  },
];
